backend => back-end
FriendsOfTYPO3/extension_builder pull request #273
Opened 2020-05-03 15:46 UTC by franzholz

The extension key can have an underline character "_ " inside of its name.

2020-05-05 20:11 UTC, franzholz commented
The terms "frontend" and "backend" do not exist in any English dictionary. They are only German Denglish words. It is written wrongly on many places.

Look here:

https://www.thefreedictionary.com/Backend
https://en.bab.la/dictionary/english-german/backend
https://www.oxfordlearnersdictionaries.com/definition/english/back-end_2?q=backend
https://www.dictionary.com/misspelling?term=backend&s=t
https://de.langenscheidt.com/englisch-deutsch/search?term=backend&q_cat=%2Fenglisch-deutsch%2F
https://www.dict.cc/?s=backend

2020-05-05 20:15 UTC, nicodh commented
Yes I know but the question is if we stick to the (wrong) TYPO3 wording convention since our context is the TYPO3 eco system...

2020-05-05 20:17 UTC, simonschaufi commented
I always thought that it is one word

2020-05-05 20:52 UTC, liayn commented
There has been a decision that these artificially crafted words Frontend and Backend should be used like this. Please contact the documentation team on Slack to cross-check with their knowledge and guidelines.

2020-09-15 13:41 UTC, gilbertsoft commented
Also see https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/Glossary.html

2020-09-15 14:59 UTC, DavidBruchmann commented
> There has been a decision that these artificially crafted words Frontend and Backend should be used like this.

yes the page linked by @gilbertsoft explains they shall be used not capitalized.

I'd say, back to the end - front or back ;-)

2020-09-16 07:47 UTC, liayn requested changes

2020-09-16 07:47 UTC, liayn commented on Documentation/Developer/Index.rst
> ++--------+---------------------------------------------------------+
This is a broken table layout

2020-09-16 07:47 UTC, liayn commented on Documentation/Developer/Index.rst
> +```````````````````````
one too much

2020-09-16 07:47 UTC, liayn commented on Documentation/Developer/Index.rst
> ++---------------+---------------------------------------------------------------------+
broken table

2020-09-18 06:41 UTC, liayn approved these changes

2020-09-18 06:46 UTC, merged