Declare strict 53
FriendsOfTYPO3/extension_builder pull request #320
Opened 2020-09-26 21:54 UTC by nicodh

2020-09-26 22:10 UTC, nicodh commented
Not sure if there might be cases where someone does not want the declare strict types - so I made it configurable...

2020-09-27 21:24 UTC, liayn submitted a review, later dismissed

2020-09-27 21:29 UTC, simonschaufi requested changes

2020-09-27 21:29 UTC, simonschaufi commented on Classes/Service/FileGenerator.php
> +    protected function writeClassFile($classFileObject) {
This is not PSR-2 standard formatted

2020-09-27 21:35 UTC, simonschaufi requested changes

2020-09-27 21:35 UTC, simonschaufi commented on Classes/Parser/NodeFactory.php
> +        } else {
I would turn this upside down to make it more like "return early if possible":

```php
if (! ...) {
    return $stmts = $this->getContainerStatements($fileObject);
}
foreach(...)
```

2020-09-29 14:17 UTC, simonschaufi commented
Use the Plugin "PHP Inspections (EA Extended)"

2020-09-29 17:25 UTC, nicodh commented
Ok - changed it but imho it does not improve readability that much...

2020-09-29 19:26 UTC, simonschaufi approved these changes

2020-09-29 19:27 UTC, merged