Persistence classes
FriendsOfTYPO3/extension_builder pull request #323
Opened 2020-11-11 22:38 UTC by nicodh

Adaptions to this breaking change: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

2020-11-11 23:20 UTC, simonschaufi requested changes

2020-11-11 23:20 UTC, simonschaufi commented on Classes/Configuration/ExtensionBuilderConfigurationManager.php
> +    public function getExtensionSettings(string $extensionKey, string $extensionStoragePath): array
docheader is missing the new parameter

2020-11-11 23:20 UTC, simonschaufi commented on Classes/Configuration/ExtensionBuilderConfigurationManager.php
> +    public function getSettingsFile($extensionKey, $storagePath): string
docheader is missing the new parameter and it should be defined as string

2020-11-11 23:20 UTC, simonschaufi commented on Classes/Domain/Model/DomainObject.php
> +    public function getHasPropertiesWithMappingStatements()
return is bool and not array

2020-11-11 23:20 UTC, simonschaufi commented on Classes/Domain/Model/DomainObject.php
> +    */
indentation wrong

2020-11-11 23:20 UTC, simonschaufi commented on Classes/Domain/Model/DomainObject/AbstractProperty.php
> +            $statement = "'" . $this->name . "' => [\n\t'fieldName' => '". $this->getFieldName() . "'\n],";
please make this a oneliner. assigning a variable is not needed

2020-11-11 23:20 UTC, simonschaufi commented on Tests/Fixtures/TestExtensions/test_extension/ExtensionBuilder.json
> +	"storagePath": "\/var\/www\/html\/public\/typo3conf\/ext\/",
indentation looks wrong

2020-11-12 19:52 UTC, liayn commented on Classes/Domain/Model/DomainObject.php
> +     * @return boolean
it is `bool`

2020-11-13 10:37 UTC, simonschaufi requested changes

2020-11-13 10:37 UTC, simonschaufi commented on Classes/Service/FileGenerator.php
> +    public function generateExtbaseConfigClass() {
this is not PSR-2. the `{` should be on the next line

2020-11-13 10:37 UTC, simonschaufi commented on Classes/Service/FileGenerator.php
> +
remove empty line

2020-11-13 10:37 UTC, simonschaufi commented on Classes/Service/FileGenerator.php
> +
remove empty line

2020-11-13 10:37 UTC, simonschaufi commented on Classes/Configuration/ExtensionBuilderConfigurationManager.php
> +    public function getSettingsFile($extensionKey, $storagePath): string
please define the parameter type also directly in the method

2020-12-02 19:38 UTC, merged