Add new feature to rename the table
FriendsOfTYPO3/extension_builder pull request #417
Opened 2021-07-08 08:42 UTC by franzholz

Similar to mapToTable, however no table needs to exist.

2021-07-13 21:07 UTC, simonschaufi commented
- Tests missing
- This file must be generated in order for it to work: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

2021-07-13 21:07 UTC, simonschaufi requested changes
This is still far away from being reviewed.

- Tests missing
- This file must be generated in order for it to work: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html with the  `tableName` mapping

2021-07-13 21:09 UTC, simonschaufi commented on Resources/Private/Language/locallang.xlf
> +<file source-language="en" datatype="plaintext" original="EXT:extension_builder/Resources/Private/Language/locallang.xlf" date="2012-02-29T20:52:35Z"
please revert this change.

2021-07-17 19:44 UTC, franzholz commented on Resources/Private/Language/locallang.xlf
> +<file source-language="en" datatype="plaintext" original="EXT:extension_builder/Resources/Private/Language/locallang.xlf" date="2012-02-29T20:52:35Z"
undone

2021-07-19 07:39 UTC, franzholz commented
In the meantime, 2 days ago, the tests have changed.
So I can hardly add the tests to this patch which is based on an older version of the code.

2021-07-19 07:48 UTC, simonschaufi commented
Just rebase on master and force push.

2024-03-24 12:25 UTC, PKuhlmay commented
I will close this, as the GUI had changed completely and the old JS is not used anymore. If you still need this for v12, then please create an issue for this.

2024-03-24 12:25 UTC, closed without merging